### ISSUE TITLE
MenuButtonHorizontalRule producing console warnings

### ISSUE THREAD

**Issue by yudielcurbelo** [sjdemartini/mui-tiptap#103]
### Describe the bug

Warnings in the console.

### To Reproduce

1. Add Menu `<MenuButtonHorizontalRule />`

### Expected behavior

Should not have warnings.

### Logs

```
react_devtools_backend_compact.js:13096 TextSelection endpoint not pointing into a node with inline content (doc) 
    at MenuButtonHorizontalRule (webpack-internal:///./node_modules/mui-tiptap/dist/esm/controls/MenuButtonHorizontalRule.js:16:86)
    at div
    at MenuControlsContainer (webpack-internal:///./node_modules/mui-tiptap/dist/esm/controls/MenuControlsContainer.js:26:34)
    at Menu (webpack-internal:///./src/components/RichText/Menu.tsx:16:88)
    at DebounceRender (webpack-internal:///./node_modules/mui-tiptap/dist/esm/utils/DebounceRender.js:39:9)
    at div
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-c39617d8.browser.esm.js:60:66)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-c39617d8.browser.esm.js:60:66)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-c39617d8.browser.esm.js:60:66)
    at Transition (webpack-internal:///./node_modules/react-transition-group/esm/Transition.js:133:30)
    at Collapse (webpack-internal:///./node_modules/@mui/material/Collapse/Collapse.js:115:82)
    at MenuBar (webpack-internal:///./node_modules/mui-tiptap/dist/esm/MenuBar.js:43:20)
    at div
    at FieldContainer (webpack-internal:///./node_modules/mui-tiptap/dist/esm/FieldContainer.js:70:27)
    at RichTextField (webpack-internal:///./node_modules/mui-tiptap/dist/esm/RichTextField.js:67:26)
    at RichTextEditorProvider (webpack-internal:///./node_modules/mui-tiptap/dist/esm/RichTextEditorProvider.js:18:35)
    at RichTextEditor (webpack-internal:///./node_modules/mui-tiptap/dist/esm/RichTextEditor.js:27:100)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-c39617d8.browser.esm.js:60:66)
    at Box (webpack-internal:///./node_modules/@mui/system/esm/createBox.js:37:72)
    at eval (webpack-internal:///./src/components/RichText/RichText.tsx:22:13)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-c39617d8.browser.esm.js:60:66)
    at Grid (webpack-internal:///./node_modules/@mui/system/esm/Stack/createStack.js:153:24)
    at form
    at Form (webpack-internal:///./src/components/forms/Form.tsx:15:13)
    at FormProvider (webpack-internal:///./node_modules/react-hook-form/dist/index.esm.mjs:180:13)
    at FormContainer (webpack-internal:///./src/components/forms/FormContainer.tsx:53:13)
    at Form (webpack-internal:///./src/views/calendar/Form.tsx:70:13)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-c39617d8.browser.esm.js:60:66)
    at Box (webpack-internal:///./node_modules/@mui/system/esm/createBox.js:37:72)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-c39617d8.browser.esm.js:60:66)
    at Paper (webpack-internal:///./node_modules/@mui/material/Paper/Paper.js:79:83)
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-c39617d8.browser.esm.js:60:66)
    at Transition (webpack-internal:///./node_modules/react-transition-group/esm/Transition.js:133:30)
    at Slide (webpack-internal:///./node_modules/@mui/material/Slide/Slide.js:98:77)
    at FocusTrap (webpack-internal:///./node_modules/@mui/base/FocusTrap/FocusTrap.js:95:5)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-c39617d8.browser.esm.js:60:66)
    at Portal (webpack-internal:///./node_modules/@mui/base/Portal/Portal.js:36:5)
    at Modal (webpack-internal:///./node_modules/@mui/base/Modal/Modal.js:81:7)
    at Modal (webpack-internal:///./node_modules/@mui/material/Modal/Modal.js:83:82)
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-c39617d8.browser.esm.js:60:66)
    at Drawer (webpack-internal:///./node_modules/@mui/material/Drawer/Drawer.js:155:83)
    at SidebarRight (webpack-internal:///./src/views/calendar/SidebarRight.tsx:27:13)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-c39617d8.browser.esm.js:60:66)
    at Box (webpack-internal:///./node_modules/@mui/system/esm/createBox.js:37:72)
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-c39617d8.browser.esm.js:60:66)
    at Container (webpack-internal:///./src/views/calendar/Container.tsx:36:90)
    at Calendar
    at main
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-c39617d8.browser.esm.js:60:66)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-c39617d8.browser.esm.js:60:66)
    at Box (webpack-internal:///./node_modules/@mui/system/esm/createBox.js:37:72)
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-c39617d8.browser.esm.js:60:66)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-c39617d8.browser.esm.js:60:66)
    at VerticalLayout (webpack-internal:///./src/@core/layouts/VerticalLayout.tsx:79:13)
    at Layout (webpack-internal:///./src/@core/layouts/Layout.tsx:18:13)
    at UserLayout (webpack-internal:///./src/layouts/UserLayout.tsx:33:11)
    at LocalizationProvider (webpack-internal:///./node_modules/@mui/x-date-pickers/LocalizationProvider/LocalizationProvider.js:32:19)
    at AuthGuard (webpack-internal:///./src/layouts/auth/AuthGuard.tsx:21:13)
    at Direction (webpack-internal:///./src/layouts/components/Direction.tsx:30:13)
    at ThemeProvider (webpack-internal:///./node_modules/@mui/private-theming/ThemeProvider/ThemeProvider.js:43:5)
    at ThemeProvider (webpack-internal:///./node_modules/@mui/system/esm/ThemeProvider/ThemeProvider.js:54:5)
    at ThemeProvider (webpack-internal:///./node_modules/@mui/material/styles/ThemeProvider.js:27:14)
    at ThemeComponent (webpack-internal:///./src/@core/theme/ThemeComponent.tsx:27:13)
    at SettingsProvider (webpack-internal:///./src/@core/context/settingsContext.tsx:76:11)
    at QueryClientProvider (webpack-internal:///./node_modules/@tanstack/react-query/build/lib/QueryClientProvider.mjs:48:3)
    at App (webpack-internal:///./pages/_app.tsx:85:13)
    at PathnameContextProviderAdapter (webpack-internal:///./node_modules/next/dist/shared/lib/router/adapters.js:74:11)
    at ErrorBoundary (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:306:63)
    at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:858:919)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:92:1)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:197:11)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:380:11)
```

### System (please complete the following information):

- mui-tiptap version: [1.0.0]
- tiptap version: [2.0.3]
- Browser: [Chrome]
- Node version: [18.16.1]
- OS: [Windows 11]

**Comment by sjdemartini** [comment]
Thanks @yudielcurbelo for the report. Agreed this is annoying. Unfortunately this console warning is due to a problem in Tiptap itself https://github.com/ueberdosis/tiptap/issues/3003. I'm going to close as won't fix, since any change to resolve this problem will likely need to be made within Tiptap. Please upvote that linked issue and/or chime in there with more info if needed! Would be great for this to get fixed! 

If you happen to have suggestions for ways this can be avoided within mui-tiptap in the meantime, do let me know!
