### ISSUE TITLE
Demo fails to build

### ISSUE THREAD

**Issue by clibu** [sjdemartini/mui-tiptap#255]
### Describe the bug

In https://www.npmjs.com/package/mui-tiptap click on "Demo" which opens https://codesandbox.io/p/devbox/mui-tiptap-demo-3zl2l6

Codesandbox terminal shows:
7:28:52 AM [vite] Internal server error: Cannot read properties of undefined (reading '0')
      at Context.load (file:///project/workspace/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:37051:65)
      at Object.load (file:///project/workspace/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:42892:46)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async loadAndTransform (file:///project/workspace/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:53318:24)

### Expected behavior

Demo to build and run

**Comment by sjdemartini** [comment]
Thanks for filing, strange! Nothing has changed in the CodeSandbox for a while, so I guess something changed on CodeSandbox's side. I'll try to take a look and resolve soon.

**Comment by sjdemartini** [comment]
@clibu I've updated the linked CodeSandbox to use the latest CodeSandbox microvm and editor (which is based on VSCode), and it seems to be working smoothly again now. Let me know if you still have any issue on your end!

**Comment by clibu** [comment]
@sjdemartini All fine now.
